/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSST007_1_CUS13.pll;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author praveen
 */
public class Accounts_Expense_Voucher_Edit extends javax.swing.JInternalFrame {

    private static Accounts_Expense_Voucher_Edit instance;
    expensedetails_jt_listSelectionListener pnt = new expensedetails_jt_listSelectionListener();
    
    int initial_status;
    int current_status;
    String initial_bank;
    BigDecimal initial_amount;
    
    public Accounts_Expense_Voucher_Edit() {
        initComponents();
    }

    public static Accounts_Expense_Voucher_Edit getInstance()
    {
        
        if (instance == null)
            instance = new Accounts_Expense_Voucher_Edit();

        return instance;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        voucherno_jcb = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        expensedetails_jt = new javax.swing.JTable();
        showdetails_jb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        expenseType_jcb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        expenseItem_jcb = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        description_jtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        to_jtf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date_jtf = new com.toedter.calendar.JDateChooser();
        amount_jtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        from_bank_jchkbx = new javax.swing.JCheckBox();
        banklist_jcb = new javax.swing.JComboBox();
        from_cash_jchkbx = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        edit_jb = new javax.swing.JButton();
        update_jb = new javax.swing.JButton();
        close_jb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        setClosable(true);
        setTitle("View/Edit -> Expenses");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/DSST007_1_CUS13/InstabizTrader Logo Final 35x35.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener()
        {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
            {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
            {
            }
        });

        jPanel1.setBackground(new java.awt.Color(242, 242, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Voucher No :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 2, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        voucherno_jcb.setEditable(true);
        voucherno_jcb.setPreferredSize(new java.awt.Dimension(200, 25));
        voucherno_jcb.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                voucherno_jcbActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        jPanel1.add(voucherno_jcb, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(858, 350));

        expensedetails_jt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        expensedetails_jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "SNo", "Date", "ExpenseType", "ExpenseItem", "Description", "To", "Amount", "id"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        expensedetails_jt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        expensedetails_jt.setFillsViewportHeight(true);
        expensedetails_jt.setRowHeight(23);
        expensedetails_jt.setSelectionBackground(new java.awt.Color(86, 132, 191));
        expensedetails_jt.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                expensedetails_jtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                expensedetails_jtFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(expensedetails_jt);
        if (expensedetails_jt.getColumnModel().getColumnCount() > 0)
        {
            expensedetails_jt.getColumnModel().getColumn(0).setMinWidth(50);
            expensedetails_jt.getColumnModel().getColumn(0).setPreferredWidth(50);
            expensedetails_jt.getColumnModel().getColumn(1).setMinWidth(100);
            expensedetails_jt.getColumnModel().getColumn(1).setPreferredWidth(100);
            expensedetails_jt.getColumnModel().getColumn(2).setMinWidth(150);
            expensedetails_jt.getColumnModel().getColumn(2).setPreferredWidth(150);
            expensedetails_jt.getColumnModel().getColumn(3).setMinWidth(150);
            expensedetails_jt.getColumnModel().getColumn(3).setPreferredWidth(150);
            expensedetails_jt.getColumnModel().getColumn(4).setMinWidth(150);
            expensedetails_jt.getColumnModel().getColumn(4).setPreferredWidth(150);
            expensedetails_jt.getColumnModel().getColumn(5).setMinWidth(150);
            expensedetails_jt.getColumnModel().getColumn(5).setPreferredWidth(150);
            expensedetails_jt.getColumnModel().getColumn(6).setMinWidth(100);
            expensedetails_jt.getColumnModel().getColumn(6).setPreferredWidth(100);
            expensedetails_jt.getColumnModel().getColumn(7).setMinWidth(0);
            expensedetails_jt.getColumnModel().getColumn(7).setPreferredWidth(0);
            expensedetails_jt.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        showdetails_jb.setBackground(new java.awt.Color(185, 197, 31));
        showdetails_jb.setText("Show Details");
        showdetails_jb.setPreferredSize(new java.awt.Dimension(110, 27));
        showdetails_jb.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                showdetails_jbMouseClicked(evt);
            }
        });
        showdetails_jb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                showdetails_jbKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 5);
        jPanel1.add(showdetails_jb, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(242, 242, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Expense Category  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        expenseType_jcb.setEnabled(false);
        expenseType_jcb.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(expenseType_jcb, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Expense Item :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 45, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        expenseItem_jcb.setEnabled(false);
        expenseItem_jcb.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(expenseItem_jcb, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(242, 242, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Description :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        description_jtf.setEnabled(false);
        description_jtf.setPreferredSize(new java.awt.Dimension(300, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(description_jtf, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("To :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        to_jtf.setEnabled(false);
        to_jtf.setPreferredSize(new java.awt.Dimension(300, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(to_jtf, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(242, 242, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Date :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        date_jtf.setBackground(new java.awt.Color(242, 242, 255));
        date_jtf.setDateFormatString("d-MMM- y");
        date_jtf.setEnabled(false);
        date_jtf.setPreferredSize(new java.awt.Dimension(140, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(date_jtf, gridBagConstraints);

        amount_jtf.setEnabled(false);
        amount_jtf.setPreferredSize(new java.awt.Dimension(110, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(amount_jtf, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Amount :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 139, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 52, 0, 0);
        jPanel2.add(jPanel4, gridBagConstraints);

        from_bank_jchkbx.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        from_bank_jchkbx.setText("From Bank :");
        from_bank_jchkbx.setEnabled(false);
        from_bank_jchkbx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                from_bank_jchkbxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(from_bank_jchkbx, gridBagConstraints);

        banklist_jcb.setEditable(true);
        banklist_jcb.setEnabled(false);
        banklist_jcb.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(banklist_jcb, gridBagConstraints);

        from_cash_jchkbx.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        from_cash_jchkbx.setText("From Cash");
        from_cash_jchkbx.setEnabled(false);
        from_cash_jchkbx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                from_cash_jchkbxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(from_cash_jchkbx, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jSeparator1, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(242, 242, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        edit_jb.setBackground(new java.awt.Color(185, 197, 31));
        edit_jb.setText("Edit");
        edit_jb.setPreferredSize(new java.awt.Dimension(100, 27));
        edit_jb.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                edit_jbMouseClicked(evt);
            }
        });
        edit_jb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                edit_jbKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(edit_jb, gridBagConstraints);

        update_jb.setBackground(new java.awt.Color(185, 197, 31));
        update_jb.setText("Update");
        update_jb.setEnabled(false);
        update_jb.setPreferredSize(new java.awt.Dimension(100, 27));
        update_jb.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                update_jbMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel5.add(update_jb, gridBagConstraints);

        close_jb.setBackground(new java.awt.Color(86, 132, 191));
        close_jb.setText("Close");
        close_jb.setPreferredSize(new java.awt.Dimension(100, 27));
        close_jb.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                close_jbMouseClicked(evt);
            }
        });
        close_jb.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                close_jbKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel5.add(close_jb, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 0);
        jPanel1.add(jPanel5, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(185, 197, 31));
        jButton1.setText("Show All");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 27));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jButton1KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 2, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 862, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
        instance = null;
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        
        instance = null;
        
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        
        Dimension desktopSize = NewMDIApplication.desktopbg_jlbl.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        //-----------------------------------
        
        load_voucherno_jcb();
        AutoCompleteDecorator.decorate(voucherno_jcb);
        
        load_banklist_jcb();
        AutoCompleteDecorator.decorate(banklist_jcb);
        
        load_expenseType_jcb();
        load_expenseItem_jcb();
           
    }//GEN-LAST:event_formInternalFrameOpened

    void load_banklist_jcb()
    {
        
        Connection con = DatabaseConnection.createConnection();
        PreparedStatement prepstmt = null;
        banklist_jcb.removeAllItems();

        try {
            
            String sql = "SELECT DISTINCT bank_name FROM banks";
            prepstmt = con.prepareStatement(sql);
            ResultSet rs = prepstmt.executeQuery();
            while (rs.next()) {

                String banknames = rs.getString("bank_name");
               
                banklist_jcb.addItem(banknames);

            }
            
            banklist_jcb.addItem("");
            banklist_jcb.setSelectedItem("");
           
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        } finally {

            if (con != null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            
            if (prepstmt != null) {
                try {
                    prepstmt.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            
            
        }       
        
    }
    
    private void load_expenseType_jcb()
    {
        
        Connection con = DatabaseConnection.createConnection();
        
         
        try
        {
            boolean stat = false;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT DISTINCT expense_type FROM expense_types ");
            
            while(rs.next())
            {

                String expense_type = rs.getString("expense_type");
                expenseType_jcb.addItem(expense_type);
                
            }    
      
            expenseType_jcb.addItem("");
            expenseType_jcb.setSelectedItem("");
            
        }
        catch(Exception e)
        {
             
            JOptionPane.showMessageDialog(null, e);
             
        }
        finally
                {
                    
                    if(con!=null)
                    {
                        try {
                            con.close();
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex);
                        }
                        
                    }
                    
                }
        
    }
    
    private void load_expenseItem_jcb()
    {
        
        Connection con = DatabaseConnection.createConnection();
        
         
        try
        {
            boolean stat = false;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT DISTINCT expense_item FROM expense_items ");
            
            while(rs.next())
            {

                String expense_item = rs.getString("expense_item");
                expenseItem_jcb.addItem(expense_item);
                
            }    
      
            expenseItem_jcb.addItem("");
            expenseItem_jcb.setSelectedItem("");
            
        }
        catch(Exception e)
        {
             
            JOptionPane.showMessageDialog(null, e);
             
        }
        finally
                {
                    
                    if(con!=null)
                    {
                        try {
                            con.close();
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex);
                        }
                        
                    }
                    
                }
        
    }
    
    private void close_jbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_close_jbKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {

            this.dispose();

        }

    }//GEN-LAST:event_close_jbKeyPressed

    private void close_jbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_jbMouseClicked

        this.dispose();

    }//GEN-LAST:event_close_jbMouseClicked

    private void update_jbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_jbMouseClicked

        if(update_jb.isEnabled())
        {

            if(validation_on_update() == true)
            {

                update();

            }

        }

    }//GEN-LAST:event_update_jbMouseClicked

    private void edit_jbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edit_jbKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {

            if(expensedetails_jt.getSelectedRow() == -1)
            {

                JOptionPane.showMessageDialog(this,"Select a row to Edit.","Error",JOptionPane.ERROR_MESSAGE);

            }
            else
            {

                enabled();

            }

        }

    }//GEN-LAST:event_edit_jbKeyPressed

    private void edit_jbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_jbMouseClicked

        if(expensedetails_jt.getSelectedRow() == -1)
        {

            JOptionPane.showMessageDialog(this,"Select a row to Edit.","Error",JOptionPane.ERROR_MESSAGE);

        }
        else
        {

            enabled();

        }

    }//GEN-LAST:event_edit_jbMouseClicked

    private void showdetails_jbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showdetails_jbKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {

            if(voucherno_jcb.getSelectedIndex() == -1)
            {

                JOptionPane.showMessageDialog(this,"Select a valid Voucher Number.","Error",JOptionPane.ERROR_MESSAGE); 

            }
            else
            {

                viewdetail();

            }

        }

    }//GEN-LAST:event_showdetails_jbKeyPressed

    private void showdetails_jbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showdetails_jbMouseClicked
        // TODO add your handling code here:

        if(voucherno_jcb.getSelectedIndex() == -1)
        {
            
            JOptionPane.showMessageDialog(this,"Select a valid Voucher Number.","Error",JOptionPane.ERROR_MESSAGE); 
            
        }
        else
        {
            
            viewdetail();
            
        }
        
       

    }//GEN-LAST:event_showdetails_jbMouseClicked

    private void expensedetails_jtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expensedetails_jtFocusLost

        ListSelectionModel selectionModel = expensedetails_jt.getSelectionModel();
        selectionModel.removeListSelectionListener(pnt);

    }//GEN-LAST:event_expensedetails_jtFocusLost

    private void expensedetails_jtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expensedetails_jtFocusGained

        ListSelectionModel selectionModel = expensedetails_jt.getSelectionModel();
        selectionModel.addListSelectionListener(pnt);

    }//GEN-LAST:event_expensedetails_jtFocusGained

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
         viewList();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void voucherno_jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucherno_jcbActionPerformed
        // TODO add your handling code here:
        
        ((DefaultTableModel)expensedetails_jt.getModel()).setRowCount(0);
        expenseType_jcb.setSelectedItem("");
        expenseItem_jcb.setSelectedItem("");
        description_jtf.setText("");
        to_jtf.setText("");
        date_jtf.setDate(null);
        amount_jtf.setText("");
        
    }//GEN-LAST:event_voucherno_jcbActionPerformed

    private void from_bank_jchkbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_bank_jchkbxActionPerformed
        // TODO add your handling code here:
        
        if(from_bank_jchkbx.isSelected() == true)
        {
            
            banklist_jcb.setEnabled(true);
            from_cash_jchkbx.setSelected(false);
            
        }
        
    }//GEN-LAST:event_from_bank_jchkbxActionPerformed

    private void from_cash_jchkbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_cash_jchkbxActionPerformed
        // TODO add your handling code here:
        
        if(from_cash_jchkbx.isSelected() == true)
        {
            
            from_bank_jchkbx.setSelected(false);
            banklist_jcb.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_from_cash_jchkbxActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
            viewList();
            
        }
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void load_voucherno_jcb()
    {
        
        Connection con = DatabaseConnection.createConnection();
        
         
        try
        {
            boolean stat = false;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT DISTINCT voucher_no FROM expense_voucher ");
            
            while(rs.next())
            {

                String voucher_no = rs.getString("voucher_no");
                voucherno_jcb.addItem(voucher_no);
                
            }    
      
            voucherno_jcb.setSelectedItem("");
            
        }
        catch(Exception e)
        {
             
            JOptionPane.showMessageDialog(null, e);
             
        }
        finally
                {
                    
                    if(con!=null)
                    {
                        try {
                            con.close();
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex);
                        }
                        
                    }
                    
                }
        
    }
    
    private void enabled(){
    
        expenseType_jcb.setEnabled(true);
        expenseItem_jcb.setEnabled(true);
        description_jtf.setEnabled(true);
        to_jtf.setEnabled(true);
        date_jtf.setEnabled(true);
        amount_jtf.setEnabled(true);
        update_jb.setEnabled(true);
        banklist_jcb.setEnabled(true);
        from_bank_jchkbx.setEnabled(true);
        from_cash_jchkbx.setEnabled(true);
        ((JTextField)date_jtf.getDateEditor().getUiComponent()).setBackground(Color.white);
        
    }
    private boolean validation_on_update()
    {
        
        boolean valid = true;
        
        if(expenseType_jcb.getSelectedItem() == null || expenseType_jcb.getSelectedItem().toString().equals(""))
        {

            JOptionPane.showMessageDialog(this,"Specify a valid Expense Type.","Error",JOptionPane.ERROR_MESSAGE); 
            valid = false;

        }
        else if(expenseItem_jcb.getSelectedItem() == null || expenseItem_jcb.getSelectedItem().toString().equals(""))
        {

            JOptionPane.showMessageDialog(this,"Specify a valid Expense Item.","Error",JOptionPane.ERROR_MESSAGE); 
            valid = false;

        }
//        else if(description_jtf.getText().equals(""))
//        {
//
//            JOptionPane.showMessageDialog(this,"Enter a Description for this transaction.","Error",JOptionPane.ERROR_MESSAGE); 
//            valid = false;
//
//        }
        else if(date_jtf.getDate() == null)
        {

            JOptionPane.showMessageDialog(this,"Specify a Date.","Error",JOptionPane.ERROR_MESSAGE); 
            valid = false;

        }
        else if(amount_jtf.getText().equals(""))
        {

            JOptionPane.showMessageDialog(this,"Specify an Amount.","Error",JOptionPane.ERROR_MESSAGE); 
            valid = false;

        }
        else if(banklist_jcb.getSelectedItem() == null || banklist_jcb.getSelectedItem().toString().equals(""))
        {

            JOptionPane.showMessageDialog(this,"Specify a Bank.","Error",JOptionPane.ERROR_MESSAGE); 
            valid = false;

        }
        else if(banklist_jcb.getSelectedIndex() == -1)
        {

            JOptionPane.showMessageDialog(this,"Select a Bank from The List.","Error",JOptionPane.ERROR_MESSAGE); 
            valid = false;

        }
        
        return valid;
        
    }
    
    private void update()
    {
        
        boolean error = false;
        boolean status = false;
        Connection conn = DatabaseConnection.createConnection();
        
        PreparedStatement prepstat_1 = null;
        ResultSet rs_1 = null;
        
        try 
        {
             
            int row = expensedetails_jt.getSelectedRow();
            String id = expensedetails_jt.getModel().getValueAt(row, 7).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
            String entry_date = sdf.format(date_jtf.getDate());
             
            String to_bank = null;
            String to_cash = null;
            BigDecimal current_amount = new BigDecimal(amount_jtf.getText());
             
                if(from_bank_jchkbx.isSelected() == true)
                {

                    to_bank = banklist_jcb.getSelectedItem().toString();
                    to_cash = "NA";
                    current_status = 1;


                }
                else if(from_cash_jchkbx.isSelected() == true)
                {

                    to_bank = "NA";
                    to_cash = "yes";
                    current_status = 2;
                    
                }
                
                
                if(initial_status != current_status)
                {
                    
                    if(initial_amount.compareTo(current_amount) != 0)
                    {
                        
                        JOptionPane.showMessageDialog(this,"You cannot transfer and change the Amount at the same time.\nExecute the Transfer first, then update the Amount.","Error",JOptionPane.ERROR_MESSAGE);
                        
                    }
                    else
                    {
                        if(current_status == 1)
                        {

                            BigDecimal amount = new BigDecimal(amount_jtf.getText());
                            BigDecimal amt_from_cash = new BigDecimal("0");
                            BigDecimal amt_from_bank = new BigDecimal("0");
                            BigDecimal new_amount_bank = new BigDecimal("0");
                            BigDecimal new_amount_cash = new BigDecimal("0");
                            boolean cash_at_bank_found = false;

                            String sql_1 = "SELECT amount FROM cash_at_hand_acc";
                            prepstat_1 = conn.prepareStatement(sql_1);
                            rs_1 = prepstat_1.executeQuery();

                            while(rs_1.next())
                            {

                                amt_from_cash = new BigDecimal(rs_1.getString("amount"));
                                new_amount_cash = amt_from_cash.add(amount);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            String bank_selected = banklist_jcb.getSelectedItem().toString();

                            String sql_2 = "SELECT amount FROM cash_at_bank_acc WHERE bank_name=? ";
                            prepstat_1 = conn.prepareStatement(sql_2);
                            prepstat_1.setString(1, bank_selected);
                            rs_1 = prepstat_1.executeQuery();
                            while(rs_1.next())
                            {

                                cash_at_bank_found = true;

                                amt_from_bank = new BigDecimal(rs_1.getString("amount"));
                                new_amount_bank = amt_from_bank.subtract(amount);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            System.out.println(amt_from_bank.compareTo(amount));
                

                            if(cash_at_bank_found == true)
                            {

                                if(amt_from_bank.compareTo(amount) == -1)
                                {

                                    JOptionPane.showMessageDialog(this,"Not Enough Balance in Bank.","Error",JOptionPane.ERROR_MESSAGE);

                                }
                                else
                                {
                                    String sql_3 = "UPDATE cash_at_bank_acc SET bank_name=?, amount=? WHERE bank_name =? ";
                                    prepstat_1 = conn.prepareStatement(sql_3);
                                    prepstat_1.setString(1, bank_selected);
                                    prepstat_1.setString(2, new_amount_bank.toString());
                                    prepstat_1.setString(3, bank_selected);
                                    prepstat_1.executeUpdate();
                                    prepstat_1.close();

                                    String sql_4 = "UPDATE cash_at_hand_acc SET amount=? ";
                                    prepstat_1 = conn.prepareStatement(sql_4);
                                    prepstat_1.setString(1, new_amount_cash.toString());
                                    prepstat_1.executeUpdate();
                                    prepstat_1.close();

                                    
                                    String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                                    prepstat_1 = conn.prepareStatement(sql_7);
                                    prepstat_1.setString(1,entry_date);
                                    prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                                    prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                                    prepstat_1.setString(4,description_jtf.getText());
                                    prepstat_1.setString(5,to_jtf.getText()); 
                                    prepstat_1.setString(6,amount_jtf.getText());
                                    prepstat_1.setString(7,to_bank);
                                    prepstat_1.setString(8,to_cash);
                                    prepstat_1.executeUpdate(); 

                                    prepstat_1.close();

                                     status = true; 
                                }

                            }
                            else if(cash_at_bank_found == false)
                            {

                                JOptionPane.showMessageDialog(this,"Not Enough Balance in Bank.","Error",JOptionPane.ERROR_MESSAGE);
                         
                            }
                            
                        }
                        else if(current_status == 2)
                        {

                            BigDecimal amount = new BigDecimal(amount_jtf.getText());
                            BigDecimal amt_from_cash = new BigDecimal("0");
                            BigDecimal amt_from_bank = new BigDecimal("0");
                            BigDecimal new_amount_bank = new BigDecimal("0");
                            BigDecimal new_amount_cash = new BigDecimal("0");
                            boolean cash_at_hand_found = false;
                            String bank_selected = banklist_jcb.getSelectedItem().toString();

                            String sql_1 = "SELECT amount FROM cash_at_bank_acc WHERE bank_name=? ";
                            prepstat_1 = conn.prepareStatement(sql_1);
                            prepstat_1.setString(1, bank_selected);
                            rs_1 = prepstat_1.executeQuery();

                            while(rs_1.next())
                            {

                                amt_from_bank = new BigDecimal(rs_1.getString("amount"));
                                new_amount_bank = amt_from_bank.add(amount);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            String sql_2 = "SELECT amount FROM cash_at_hand_acc";
                            prepstat_1 = conn.prepareStatement(sql_2);
                            rs_1 = prepstat_1.executeQuery();
                            while(rs_1.next())
                            {

                                cash_at_hand_found = true;

                                amt_from_cash = new BigDecimal(rs_1.getString("amount"));
                                new_amount_cash = amt_from_cash.subtract(amount);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            System.out.println(amt_from_cash.compareTo(amount));

                            if(cash_at_hand_found == true)
                            {

                                if(amt_from_cash.compareTo(amount) == -1)
                                {

                                    JOptionPane.showMessageDialog(this,"Not Enough Cash in Hand.","Error",JOptionPane.ERROR_MESSAGE);

                                }
                                else
                                {
                                    String sql_3 = "UPDATE cash_at_bank_acc SET bank_name=?, amount=? WHERE bank_name =? ";
                                    prepstat_1 = conn.prepareStatement(sql_3);
                                    prepstat_1.setString(1, bank_selected);
                                    prepstat_1.setString(2, new_amount_bank.toString());
                                    prepstat_1.setString(3, bank_selected);
                                    prepstat_1.executeUpdate();
                                    prepstat_1.close();

                                    String sql_4 = "UPDATE cash_at_hand_acc SET amount=? ";
                                    prepstat_1 = conn.prepareStatement(sql_4);
                                    prepstat_1.setString(1, new_amount_cash.toString());
                                    prepstat_1.executeUpdate();
                                    prepstat_1.close();

                                    
                                    String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                                    prepstat_1 = conn.prepareStatement(sql_7);
                                    prepstat_1.setString(1,entry_date);
                                    prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                                    prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                                    prepstat_1.setString(4,description_jtf.getText());
                                    prepstat_1.setString(5,to_jtf.getText()); 
                                    prepstat_1.setString(6,amount_jtf.getText());
                                    prepstat_1.setString(7,to_bank);
                                    prepstat_1.setString(8,to_cash);
                                    prepstat_1.executeUpdate(); 

                                    prepstat_1.close();

                                     status = true; 
                                }

                            }
                            else if(cash_at_hand_found == false)
                            {

                                JOptionPane.showMessageDialog(this,"Not Enough Cash in Hand.","Error",JOptionPane.ERROR_MESSAGE);
                         
                            }

                        }
                        
                    }
                    
                }
                else
                {
                    
                    int comp = initial_amount.compareTo(current_amount);
                    BigDecimal amount = new BigDecimal(amount_jtf.getText());
                    BigDecimal amt_from_cash = new BigDecimal("0");
                    BigDecimal amt_from_bank = new BigDecimal("0");
                    BigDecimal new_amount_bank = new BigDecimal("0");
                    BigDecimal new_amount_cash = new BigDecimal("0");
                    boolean cash_at_hand_found = false;
                    String bank_selected = banklist_jcb.getSelectedItem().toString();
                    
                    BigDecimal deducted_val = null;
                    System.out.println(deducted_val);

                    if(initial_status == 1)
                    {

                        if(comp == 1)
                        {

                            deducted_val = initial_amount.subtract(amount);
                            
                            String sql_1 = "SELECT amount FROM cash_at_bank_acc WHERE bank_name=?";
                            prepstat_1 = conn.prepareStatement(sql_1);
                            prepstat_1.setString(1, bank_selected);
                            rs_1 = prepstat_1.executeQuery();
                            while(rs_1.next())
                            {

                                amt_from_bank = new BigDecimal(rs_1.getString("amount"));
                                new_amount_bank = amt_from_bank.add(deducted_val);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            String sql_6 = "UPDATE cash_at_bank_acc SET bank_name=?, amount=? WHERE bank_name =? ";
                            prepstat_1 = conn.prepareStatement(sql_6);
                            prepstat_1.setString(1, bank_selected);
                            prepstat_1.setString(2, new_amount_bank.toString());
                            prepstat_1.setString(3, bank_selected);
                            prepstat_1.executeUpdate();
                            prepstat_1.close();
                            
                            String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                            prepstat_1 = conn.prepareStatement(sql_7);
                            prepstat_1.setString(1,entry_date);
                            prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                            prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                            prepstat_1.setString(4,description_jtf.getText());
                            prepstat_1.setString(5,to_jtf.getText()); 
                            prepstat_1.setString(6,amount_jtf.getText());
                            prepstat_1.setString(7,to_bank);
                            prepstat_1.setString(8,to_cash);
                            prepstat_1.executeUpdate(); 

                            prepstat_1.close();

                            status = true;  

                        }
                        else if(comp == -1)
                        {
                            
                            deducted_val = amount.subtract(initial_amount);
                            
                            String sql_1 = "SELECT amount FROM cash_at_bank_acc WHERE bank_name=?";
                            prepstat_1 = conn.prepareStatement(sql_1);
                            prepstat_1.setString(1, bank_selected);
                            rs_1 = prepstat_1.executeQuery();
                            while(rs_1.next())
                            {

                                amt_from_bank = new BigDecimal(rs_1.getString("amount"));
                                new_amount_bank = amt_from_bank.subtract(deducted_val);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            String sql_6 = "UPDATE cash_at_bank_acc SET bank_name=?, amount=? WHERE bank_name =? ";
                            prepstat_1 = conn.prepareStatement(sql_6);
                            prepstat_1.setString(1, bank_selected);
                            prepstat_1.setString(2, new_amount_bank.toString());
                            prepstat_1.setString(3, bank_selected);
                            prepstat_1.executeUpdate();
                            prepstat_1.close();

                            String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                            prepstat_1 = conn.prepareStatement(sql_7);
                            prepstat_1.setString(1,entry_date);
                            prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                            prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                            prepstat_1.setString(4,description_jtf.getText());
                            prepstat_1.setString(5,to_jtf.getText()); 
                            prepstat_1.setString(6,amount_jtf.getText());
                            prepstat_1.setString(7,to_bank);
                            prepstat_1.setString(8,to_cash);
                            prepstat_1.executeUpdate();
                            
                            prepstat_1.close();

                            status = true;  
                            
                        }
                        else if(comp == 0)
                        {
                            
                            String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                            prepstat_1 = conn.prepareStatement(sql_7);
                            prepstat_1.setString(1,entry_date);
                            prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                            prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                            prepstat_1.setString(4,description_jtf.getText());
                            prepstat_1.setString(5,to_jtf.getText()); 
                            prepstat_1.setString(6,amount_jtf.getText());
                            prepstat_1.setString(7,to_bank);
                            prepstat_1.setString(8,to_cash);
                            prepstat_1.executeUpdate();
                            
                            prepstat_1.close();

                            status = true; 
                            
                        }
                    }
                    else if(initial_status == 2)
                    {

                        if(comp == 1)
                        {

                            deducted_val = initial_amount.subtract(amount);
                            
                            String sql_1 = "SELECT amount FROM cash_at_hand_acc ";
                            prepstat_1 = conn.prepareStatement(sql_1);
                            rs_1 = prepstat_1.executeQuery();
                            while(rs_1.next())
                            {

                                amt_from_cash = new BigDecimal(rs_1.getString("amount"));
                                new_amount_cash = amt_from_cash.add(deducted_val);

                            }

                            prepstat_1.close();
                            rs_1.close();

                            String sql_6 = "UPDATE cash_at_hand_acc SET amount=? ";
                            prepstat_1 = conn.prepareStatement(sql_6);
                            prepstat_1.setString(1, new_amount_cash.toString());
                            prepstat_1.executeUpdate();
                            prepstat_1.close();

                            String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                            prepstat_1 = conn.prepareStatement(sql_7);
                            prepstat_1.setString(1,entry_date);
                            prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                            prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                            prepstat_1.setString(4,description_jtf.getText());
                            prepstat_1.setString(5,to_jtf.getText()); 
                            prepstat_1.setString(6,amount_jtf.getText());
                            prepstat_1.setString(7,to_bank);
                            prepstat_1.setString(8,to_cash);
                            prepstat_1.executeUpdate();
                            
                            prepstat_1.close();

                            status = true;  

                        }
                        else if(comp == -1)
                        {
                            
                            deducted_val = amount.subtract(initial_amount);
                            
                            String sql_1 = "SELECT amount FROM cash_at_hand_acc ";
                            prepstat_1 = conn.prepareStatement(sql_1);
                            rs_1 = prepstat_1.executeQuery();
                            while(rs_1.next())
                            {

                                amt_from_cash = new BigDecimal(rs_1.getString("amount"));
                                new_amount_cash = amt_from_cash.subtract(deducted_val);

                            }

                            prepstat_1.close();
                            rs_1.close();
                            
                            String sql_6 = "UPDATE cash_at_hand_acc SET amount=? ";
                            prepstat_1 = conn.prepareStatement(sql_6);
                            prepstat_1.setString(1, new_amount_cash.toString());
                            prepstat_1.executeUpdate();
                            prepstat_1.close();

                            String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                            prepstat_1 = conn.prepareStatement(sql_7);
                            prepstat_1.setString(1,entry_date);
                            prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                            prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                            prepstat_1.setString(4,description_jtf.getText());
                            prepstat_1.setString(5,to_jtf.getText()); 
                            prepstat_1.setString(6,amount_jtf.getText());
                            prepstat_1.setString(7,to_bank);
                            prepstat_1.setString(8,to_cash);
                            prepstat_1.executeUpdate();
                            
                            prepstat_1.close();

                            status = true;    
                            
                        }
                        else if(comp == 0)
                        {
                            
                            String sql_7 = "UPDATE expense_voucher SET entrydate=?,expense_type=?,expense_item=?,description=?,towards=?,amount=?,from_bank=?,from_cash=? WHERE id= '"+id+"' ";
                            prepstat_1 = conn.prepareStatement(sql_7);
                            prepstat_1.setString(1,entry_date);
                            prepstat_1.setString(2,expenseType_jcb.getSelectedItem().toString());
                            prepstat_1.setString(3,expenseItem_jcb.getSelectedItem().toString());
                            prepstat_1.setString(4,description_jtf.getText());
                            prepstat_1.setString(5,to_jtf.getText()); 
                            prepstat_1.setString(6,amount_jtf.getText());
                            prepstat_1.setString(7,to_bank);
                            prepstat_1.setString(8,to_cash);
                            prepstat_1.executeUpdate();
                            
                            prepstat_1.close();

                            status = true; 
                            
                        }

                    }
                }
               
                
        } 
        catch (Exception ex) 
        {
            
            JOptionPane.showMessageDialog( null, ex);
            error = true;
                
        }
        finally
        {

            if(conn!=null)
            {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            }

        }
        if(error==false && status==true)
        {

            JOptionPane.showMessageDialog(this,"Operation Successful.","Success",JOptionPane.INFORMATION_MESSAGE);
            
            update_jb.setEnabled(false);
            disabled();
            
            ((DefaultTableModel)expensedetails_jt.getModel()).setRowCount(0);
            expenseType_jcb.setSelectedItem("");
            expenseItem_jcb.setSelectedItem("");
            description_jtf.setText("");
            to_jtf.setText("");
            date_jtf.setDate(null);
            amount_jtf.setText("");
            banklist_jcb.setSelectedItem("");
         
        }

    }
    
    private void disabled(){
    
        expenseType_jcb.setEnabled(false);
        expenseItem_jcb.setEnabled(false);
        description_jtf.setEnabled(false);
        to_jtf.setEnabled(false);
        date_jtf.setEnabled(false);
        amount_jtf.setEnabled(false);
        banklist_jcb.setEnabled(false);
        from_bank_jchkbx.setEnabled(false);
        from_cash_jchkbx.setEnabled(false);
        
    }
    
    private void viewdetail()
    {
    
        Connection conn = DatabaseConnection.createConnection();
        
        try 
        {

            DefaultTableModel dtm = (DefaultTableModel)expensedetails_jt.getModel();
            dtm.setRowCount(0);

            String voucher_no = voucherno_jcb.getSelectedItem().toString();
            
            Statement stmt = conn.createStatement();     

            String query = "SELECT id,entrydate,expense_type,expense_item,description,towards,amount FROM expense_voucher WHERE voucher_no = '"+voucher_no+"' ";

            // create the java statement
            Statement st = conn.createStatement();

            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);

            // iterate through the java resultset
            while (rs.next())
            {
              String id = rs.getString("id");
              String date = rs.getString("entrydate");
              String expense_type = rs.getString("expense_type");
              String expense_item = rs.getString("expense_item");
              String description = rs.getString("description");
              String towards = rs.getString("towards");
              String amount = rs.getString("amount");
              
              String[] nameArr = new String[]{Integer.toString(expensedetails_jt.getRowCount()+1),date,expense_type,expense_item,description,towards,amount,id};
              dtm.addRow(nameArr);

            }

        }
        catch (Exception ex) 
        {

            JOptionPane.showMessageDialog( null, ex);

        }
        finally
        {

            if(conn!=null)
            {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            }

        }
      
    }
    
    private void viewList()
    {
    
        Connection conn = DatabaseConnection.createConnection();
        
        try 
        {

            DefaultTableModel dtm = (DefaultTableModel)expensedetails_jt.getModel();
            dtm.setRowCount(0);

            Statement stmt = conn.createStatement();     

            String query = "SELECT id,entrydate,expense_type,expense_item,description,towards,amount FROM expense_voucher";

            // create the java statement
            Statement st = conn.createStatement();

            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);

            // iterate through the java resultset
            while (rs.next())
            {
              String id = rs.getString("id");
              String date = rs.getString("entrydate");
              String expense_type = rs.getString("expense_type");
              String expense_item = rs.getString("expense_item");
              String description = rs.getString("description");
              String towards = rs.getString("towards");
              String amount = rs.getString("amount");
              
              String[] nameArr = new String[]{Integer.toString(expensedetails_jt.getRowCount()+1),date,expense_type,expense_item,description,towards,amount,id};
              dtm.addRow(nameArr);

            }

        }
        catch (Exception ex) 
        {

            JOptionPane.showMessageDialog( null, ex);

        }
        finally
        {

            if(conn!=null)
            {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

            }

        }
      
    }
    
    
    class expensedetails_jt_listSelectionListener implements ListSelectionListener{

    @Override
    public void valueChanged(ListSelectionEvent e) 
    {
        
        try 
        {
            
            DefaultTableModel dtm = (DefaultTableModel)Accounts_Expense_Voucher_Edit.expensedetails_jt.getModel();
           
            int row = Accounts_Expense_Voucher_Edit.expensedetails_jt.getSelectedRow();
            String value = Accounts_Expense_Voucher_Edit.expensedetails_jt.getModel().getValueAt(row, 7).toString();

            Connection conn = DatabaseConnection.createConnection();
           
            String query = "SELECT * FROM expense_voucher WHERE id= '"+value+"' ";
           
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next())
            {
              
                String date = rs.getString("entrydate");
                String expense_type = rs.getString("expense_type");
                String expense_item = rs.getString("expense_item");
                String description = rs.getString("description");
                String towards = rs.getString("towards");
                String amount = rs.getString("amount");
                String from_bank = rs.getString("from_bank");
                String from_cash = rs.getString("from_cash");

                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                SimpleDateFormat sdf2 = new SimpleDateFormat("d-MMM-yyyy", Locale.getDefault());
                Date formatted_date = sdf2.parse(sdf2.format(sdf1.parse(date)));

                Accounts_Expense_Voucher_Edit.date_jtf.setDate(formatted_date);
                Accounts_Expense_Voucher_Edit.expenseType_jcb.setSelectedItem(expense_type);
                Accounts_Expense_Voucher_Edit.expenseItem_jcb.setSelectedItem(expense_item);
                Accounts_Expense_Voucher_Edit.description_jtf.setText(description);
                Accounts_Expense_Voucher_Edit.to_jtf.setText(towards);
                Accounts_Expense_Voucher_Edit.amount_jtf.setText(amount);  
                
                if(!from_bank.equals("NA"))
                {
                    
                    from_cash_jchkbx.setSelected(false);
                    from_bank_jchkbx.setSelected(true);
                    banklist_jcb.setSelectedItem(from_bank);
                    
                    initial_status = 1;
                    
                }
                if(!from_cash.equals("NA"))
                {
                    
                    from_cash_jchkbx.setSelected(true);
                    from_bank_jchkbx.setSelected(false);
                    banklist_jcb.setSelectedItem("");
                    
                    initial_status = 2;
                  
                }
                
                initial_bank = from_bank;
                
            }
            
            initial_amount = new BigDecimal(amount_jtf.getText());
            
        }
        catch (Exception ex) 
        {
            
            JOptionPane.showMessageDialog( null, ex);
                
        }
        
    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField amount_jtf;
    private javax.swing.JComboBox banklist_jcb;
    private javax.swing.JButton close_jb;
    public static com.toedter.calendar.JDateChooser date_jtf;
    public static javax.swing.JTextField description_jtf;
    private javax.swing.JButton edit_jb;
    public static javax.swing.JComboBox expenseItem_jcb;
    public static javax.swing.JComboBox expenseType_jcb;
    public static javax.swing.JTable expensedetails_jt;
    private javax.swing.JCheckBox from_bank_jchkbx;
    private javax.swing.JCheckBox from_cash_jchkbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton showdetails_jb;
    public static javax.swing.JTextField to_jtf;
    private javax.swing.JButton update_jb;
    private javax.swing.JComboBox voucherno_jcb;
    // End of variables declaration//GEN-END:variables
}
