/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSST007_1_CUS13.pll;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author praveen
 */
public class NewMDIApplication extends javax.swing.JFrame {

   public int w;
   public int h;
   public static File reportpath;
   public int startupwindowstatus;
   
    public NewMDIApplication(){
        initComponents();
        
        reportpath = new File(System.getProperty("user.dir"));
    
         
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();
        
        desktopbg_jlbl.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/DSST007_1_CUS13/bg_2.png")).getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(new Color(22,35,54));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        desktopbg_jlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        licence_desc_jl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar()
        {
            public void paintComponent(Graphics g)
            {
                Dimension size = jMenuBar1.getSize();
                g.drawImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/DSST007_1_CUS13/bgp5.png")), 0, 0, size.width, size.height, jMenuBar1);
            }
        }
        ;
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem36 = new javax.swing.JMenuItem();
        jSeparator25 = new javax.swing.JPopupMenu.Separator();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenuItem34 = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        jMenuItem39 = new javax.swing.JMenuItem();
        jSeparator29 = new javax.swing.JPopupMenu.Separator();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem43 = new javax.swing.JMenuItem();
        jSeparator31 = new javax.swing.JPopupMenu.Separator();
        jMenuItem44 = new javax.swing.JMenuItem();
        jSeparator30 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenuItem37 = new javax.swing.JMenuItem();
        jSeparator26 = new javax.swing.JPopupMenu.Separator();
        jMenuItem33 = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        jMenuItem35 = new javax.swing.JMenuItem();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        jMenuItem40 = new javax.swing.JMenuItem();
        jSeparator32 = new javax.swing.JPopupMenu.Separator();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem38 = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instabiz Trader");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopbg_jlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        desktopbg_jlbl.setMinimumSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(20, 114, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Licenced To :");

        licence_desc_jl.setText("Richa Combines, Rayonpuram PO, Vallam, Perumbavoor, Kerala, India - 683543");
        licence_desc_jl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        licence_desc_jl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licence_desc_jl, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(licence_desc_jl))
                .addContainerGap())
        );

        desktopPane.setLayer(desktopbg_jlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopbg_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(desktopbg_jlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(74, 40));

        jMenu7.setForeground(java.awt.Color.white);
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DSST007_1_CUS13/InstabizTrader Logo Final 35x35.png"))); // NOI18N
        jMenu7.setMnemonic('t');
        jMenu7.setText("INSTABIZ");
        jMenu7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu7);

        jMenu2.setForeground(java.awt.Color.white);
        jMenu2.setMnemonic('p');
        jMenu2.setText("Application");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem27.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem27.setText("Exit");
        jMenuItem27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem27.setBorderPainted(true);
        jMenuItem27.setPreferredSize(new java.awt.Dimension(100, 20));
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem27);

        jSeparator23.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator23.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu2.add(jSeparator23);

        jMenuItem28.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem28.setText("Log Out");
        jMenuItem28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem28.setBorderPainted(true);
        jMenuItem28.setPreferredSize(new java.awt.Dimension(100, 20));
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem28);

        jMenuBar1.add(jMenu2);

        jMenu5.setForeground(java.awt.Color.white);
        jMenu5.setMnemonic('d');
        jMenu5.setText("Admin");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem25.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem25.setText("Admin Info");
        jMenuItem25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem25.setBorderPainted(true);
        jMenuItem25.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem25);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu5.add(jSeparator1);

        jMenuItem26.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem26.setText("Change Password");
        jMenuItem26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem26.setBorderPainted(true);
        jMenuItem26.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem26);

        jSeparator24.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jMenu5.add(jSeparator24);

        jMenuItem31.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem31.setText("Back Up Database");
        jMenuItem31.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem31);

        jMenuBar1.add(jMenu5);

        jMenu3.setForeground(java.awt.Color.white);
        jMenu3.setMnemonic('a');
        jMenu3.setText("Create");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem15.setText("Customer");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu3.add(jSeparator2);

        jMenuItem17.setText("Manufacturer");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu3.add(jSeparator3);

        jMenuItem24.setText("Employee");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu3.add(jSeparator4);

        jMenuItem30.setText("Items");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem30);

        jMenuBar1.add(jMenu3);

        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setMnemonic('t');
        jMenu8.setText("Transaction");
        jMenu8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem23.setText("Print Work Order");
        jMenuItem23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem23.setBorderPainted(true);
        jMenuItem23.setPreferredSize(new java.awt.Dimension(150, 20));
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jSeparator18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator18.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu8.add(jSeparator18);

        jMenuItem36.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem36.setText("Cut Work Order");
        jMenuItem36.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem36.setBorderPainted(true);
        jMenuItem36.setPreferredSize(new java.awt.Dimension(150, 20));
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem36);

        jSeparator25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator25.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu8.add(jSeparator25);

        jMenuItem32.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem32.setText("Cut Work Statement");
        jMenuItem32.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem32.setBorderPainted(true);
        jMenuItem32.setPreferredSize(new java.awt.Dimension(150, 20));
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem32);

        jSeparator20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator20.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu8.add(jSeparator20);

        jMenuItem34.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem34.setText("Print Work Statement");
        jMenuItem34.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem34.setBorderPainted(true);
        jMenuItem34.setPreferredSize(new java.awt.Dimension(150, 20));
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem34);

        jSeparator22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator22.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu8.add(jSeparator22);

        jMenuItem39.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem39.setText("Invoice");
        jMenuItem39.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem39.setBorderPainted(true);
        jMenuItem39.setPreferredSize(new java.awt.Dimension(150, 20));
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem39);

        jSeparator29.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator29.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu8.add(jSeparator29);

        jMenuItem42.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem42.setText("Print & Delivery Queue");
        jMenuItem42.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem42.setBorderPainted(true);
        jMenuItem42.setPreferredSize(new java.awt.Dimension(150, 20));
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem42);

        jMenuBar1.add(jMenu8);

        jMenu1.setForeground(java.awt.Color.white);
        jMenu1.setMnemonic('e');
        jMenu1.setText("View/Edit");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem18.setText("Manufacturer");
        jMenuItem18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem18.setBorderPainted(true);
        jMenuItem18.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem18);

        jSeparator15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator15.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator15);

        jMenuItem43.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem43.setText("Customer");
        jMenuItem43.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem43.setBorderPainted(true);
        jMenuItem43.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem43);

        jSeparator31.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator31.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator31);

        jMenuItem44.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem44.setText("Employees");
        jMenuItem44.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem44.setBorderPainted(true);
        jMenuItem44.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem44);

        jSeparator30.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator30.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator30);

        jMenuItem21.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem21.setText("Print Work Order");
        jMenuItem21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem21.setBorderPainted(true);
        jMenuItem21.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);

        jSeparator19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator19.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator19);

        jMenuItem37.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem37.setText("Cut Work Order");
        jMenuItem37.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem37.setBorderPainted(true);
        jMenuItem37.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem37);

        jSeparator26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator26.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator26);

        jMenuItem33.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem33.setText("Cut Work Statement");
        jMenuItem33.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem33.setBorderPainted(true);
        jMenuItem33.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem33);

        jSeparator21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator21.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator21);

        jMenuItem35.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem35.setText("Print Work Statement");
        jMenuItem35.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem35.setBorderPainted(true);
        jMenuItem35.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem35);

        jSeparator27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator27.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator27);

        jMenuItem40.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem40.setText("Invoice");
        jMenuItem40.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem40.setBorderPainted(true);
        jMenuItem40.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem40);

        jSeparator32.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator32.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu1.add(jSeparator32);

        jMenuItem45.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem45.setText("Items");
        jMenuItem45.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem45.setBorderPainted(true);
        jMenuItem45.setPreferredSize(new java.awt.Dimension(145, 20));
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem45);

        jMenuBar1.add(jMenu1);

        jMenu4.setForeground(java.awt.Color.white);
        jMenu4.setMnemonic('r');
        jMenu4.setText("Reports");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem20.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem20.setText("Print Work Order");
        jMenuItem20.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jSeparator14.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu4.add(jSeparator14);

        jMenuItem19.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem19.setText("Manufacturers");
        jMenuItem19.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem19);

        jSeparator16.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu4.add(jSeparator16);

        jMenuItem22.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem22.setText("Customer");
        jMenuItem22.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jSeparator17.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu4.add(jSeparator17);

        jMenuItem38.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem38.setText("Cut Work Order");
        jMenuItem38.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem38);

        jSeparator28.setPreferredSize(new java.awt.Dimension(0, 10));
        jMenu4.add(jSeparator28);

        jMenuItem41.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem41.setText("Invoice");
        jMenuItem41.setPreferredSize(new java.awt.Dimension(135, 20));
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem41);

        jMenuBar1.add(jMenu4);

        jMenu6.setForeground(java.awt.Color.white);
        jMenu6.setMnemonic('h');
        jMenu6.setText("Help");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem29.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem29.setText("About Us");
        jMenuItem29.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jMenuItem29.setPreferredSize(new java.awt.Dimension(113, 20));
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem29);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);

        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu5);
        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu8);
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu4);
        jMenuBar1.add(jMenu6);
        
//        mbt = FloatingButtonMenu.getInstance();
//        desktopPane.add(mbt,0);
//	mbt.setVisible(true);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/DSST007_1_CUS13/InstabizTrader Logo Final 256x253.png")));
       

        startupscreen();
        
        if(LicenceCheck.istrial == true)
        {
            
            RunnableDemo R1 = new RunnableDemo( "Thread-1");
            R1.start();
            
        }

        get_licence_desc();
      
    }//GEN-LAST:event_formWindowOpened

    void get_licence_desc()
    {
        
        Connection con = DatabaseConnection.createConnection();
        
        try
        {
           
              
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery(" SELECT name FROM firm_registration ");
            if(rs1.first())
            {

               String name = rs1.getString("name");
               licence_desc_jl.setText(name);

            }
             
        }
        catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null,e);
            
        }
        finally
        {

            if(con!=null)
            {
                try {
                    con.close();
                } catch (SQLException ex) {
                    //JOptionPane.showMessageDialog(null, ex);
                    System.out.println(ex);
                }

            }
        }
        
        
    }
    
    private void startupscreen()
    {
        
        Connection con = DatabaseConnection.createConnection();
        
        try
        {
           
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(" SELECT * FROM startupwindowstatus ");
            
            if(rs.first() == false)
            {
                
                String sq2="INSERT INTO startupwindowstatus(status) values(?)";
                PreparedStatement stmt2 = con.prepareStatement(sq2);
                stmt2.setInt(1,1);
                stmt2.executeUpdate();
                
                StartupScreen ss_ = new StartupScreen();
                desktopPane.add(ss_,0);

                GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                int width = gd.getDisplayMode().getWidth();
                int height = gd.getDisplayMode().getHeight();
                //ss_.setLocation((width/2-ss_.getSize().width/2)-28, (height/2-ss_.getSize().height/2)-63);
                ss_.setLocation((width/2-ss_.getSize().width/2), (height/2-ss_.getSize().height/2)-63);
              
                BasicInternalFrameUI bi = (BasicInternalFrameUI)ss_.getUI();
                bi.setNorthPane(null);

                ss_.setVisible(true);
                
                StartupScreen.jCheckBox1.setSelected(true);
                
            }
            else
            {
                
                Statement stmt1 = con.createStatement();
                ResultSet rs1 = stmt1.executeQuery(" SELECT * FROM startupwindowstatus ");
                if(rs1.first())
                {
                    
                    if(rs1.getInt("status") == 1)
                    {
                        
                        StartupScreen ss_ = new StartupScreen();
                        desktopPane.add(ss_,0);

                        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                        int width = gd.getDisplayMode().getWidth();
                        int height = gd.getDisplayMode().getHeight();
                        //ss_.setLocation((width/2-ss_.getSize().width/2)-28, (height/2-ss_.getSize().height/2)-63);
                        ss_.setLocation((width/2-ss_.getSize().width/2), (height/2-ss_.getSize().height/2)-63);

                        BasicInternalFrameUI bi = (BasicInternalFrameUI)ss_.getUI();
                        bi.setNorthPane(null);

                        ss_.setVisible(true);
                        
                        StartupScreen.jCheckBox1.setSelected(true);
                        
                    }
                    
                    
                    
                }
                
                
            }
        
        }
        catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
            
        }
        finally
        {

            if(con!=null)
            {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                    System.out.println(ex);
                }

            }
        }
        
        
    }
    
    private void getstartupscreenstatus() {

        Connection con = DatabaseConnection.createConnection();

        try {

            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery(" SELECT * FROM startupwindowstatus ");
            if (rs1.first()) {

                if (rs1.getInt("status") == 1) {

                    startupwindowstatus = 1;

                } else if (rs1.getInt("status") == 0) {

                    startupwindowstatus = 0;

                }

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);

        } finally {

            if (con != null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                    System.out.println(ex);
                }

            }
        }

    }
    
    private void showReport() {

        try {
            Map parameters = new HashMap();

            String source = "TestReport.jasper";

            InputStream is = getClass().getResourceAsStream(source);

            String logopath = "Greenland_Logo.jpg";

            InputStream is2 = getClass().getResourceAsStream(logopath);

            parameters.put("LOGO", is2);

            JasperPrint print = JasperFillManager.fillReport(is, parameters, new JREmptyDataSource());

            JasperViewer.viewReport(print, false);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }

    }
    
    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:

        AdminInfo adminInfoForm = AdminInfo.getInstance();
        desktopPane.add(adminInfoForm,0);

        adminInfoForm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        
        Admin_ChangePassword adminChanPassForm = Admin_ChangePassword.getInstance();
        desktopPane.add(adminChanPassForm,0);

        adminChanPassForm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        
        writetrialvalue();
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
       
        writetrialvalue();
        this.setVisible(false);
        
        Login log = new Login();
        log.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        writetrialvalue();
        
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        
        //        AboutUs au = new AboutUs();
//        
//        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//        au.setLocation((dim.width/2-au.getSize().width/2)+110, dim.height/2-au.getSize().height/2);
//        
//        au.setVisible(true);
        
        getstartupscreenstatus();
        
        StartupScreen ss_ = new StartupScreen();
        desktopPane.add(ss_,0);

        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();
        //ss_.setLocation((width/2-ss_.getSize().width/2)-28, (height/2-ss_.getSize().height/2)-63);
        ss_.setLocation((width / 2 - ss_.getSize().width / 2), (height / 2 - ss_.getSize().height / 2) - 63);

        BasicInternalFrameUI bi = (BasicInternalFrameUI)ss_.getUI();
        bi.setNorthPane(null);

        ss_.setVisible(true);
        ss_.toFront();
        
        if(startupwindowstatus == 1)
        {
            
            StartupScreen.jCheckBox1.setSelected(true);
            
        }
        else if(startupwindowstatus == 0)
        {
            
            StartupScreen.jCheckBox1.setSelected(false);
            
        }
        
        
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
        
        Backupdatabase backupdb = Backupdatabase.getInstance();
        desktopPane.add(backupdb,0);

        backupdb.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        
        Customer_Registration customer_Registration = Customer_Registration.getInstance();
        desktopPane.add(customer_Registration,0);

        customer_Registration.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem17ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem17ActionPerformed
        Mfr_Registration mfr_Registration = Mfr_Registration.getInstance();
        desktopPane.add(mfr_Registration,0);

        mfr_Registration.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem18ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem18ActionPerformed
        Mfr_Registration_Edit mfr_Registration_Edit = Mfr_Registration_Edit.getInstance();
        desktopPane.add(mfr_Registration_Edit,0);

        mfr_Registration_Edit.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem19ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem19ActionPerformed
        Manufacturers_Report manufacturers_Report = Manufacturers_Report.getInstance();
        desktopPane.add(manufacturers_Report,0);

        manufacturers_Report.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem20ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem20ActionPerformed
        WorkOrderReport workOrderReport = WorkOrderReport.getInstance();
        desktopPane.add(workOrderReport,0);

        workOrderReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem21ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem21ActionPerformed
        WorkOrderEdit workOrderEdit = WorkOrderEdit.getInstance();
        desktopPane.add(workOrderEdit,0);

        workOrderEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem22ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem22ActionPerformed
        Customers_Report customers_Report = Customers_Report.getInstance();
        desktopPane.add(customers_Report,0);

        customers_Report.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem23ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem23ActionPerformed
        WorkOrderEntry workOrderEntry = WorkOrderEntry.getInstance();
        desktopPane.add(workOrderEntry,0);

        workOrderEntry.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem32ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem32ActionPerformed
        CutWorkOrderStatementEntry cutWorkOrderEstimate = CutWorkOrderStatementEntry.getInstance();
        desktopPane.add(cutWorkOrderEstimate,0);

        cutWorkOrderEstimate.setVisible(true);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem33ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem33ActionPerformed
        CutWorkOrderStatementEdit cutWorkOrderStatementEdit = CutWorkOrderStatementEdit.getInstance();
        desktopPane.add(cutWorkOrderStatementEdit,0);

        cutWorkOrderStatementEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem34ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem34ActionPerformed
        WorkOrderStatementEntry workOrderStatement = WorkOrderStatementEntry.getInstance();
        desktopPane.add(workOrderStatement,0);

        workOrderStatement.setVisible(true);
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem35ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem35ActionPerformed
        WorkOrderStatementEdit workOrderStatementEdit = WorkOrderStatementEdit.getInstance();
        desktopPane.add(workOrderStatementEdit,0);

        workOrderStatementEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem36ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem36ActionPerformed
        CutWorkOrderEntry cutWorkOrderEntry = CutWorkOrderEntry.getInstance();
        desktopPane.add(cutWorkOrderEntry,0);

        cutWorkOrderEntry.setVisible(true);
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem37ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem37ActionPerformed
        CutWorkOrderEdit cutWorkOrderEdit = CutWorkOrderEdit.getInstance();
        desktopPane.add(cutWorkOrderEdit,0);

        cutWorkOrderEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem38ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem38ActionPerformed
        CutWorkOrderReport cutWorkOrderReport = CutWorkOrderReport.getInstance();
        desktopPane.add(cutWorkOrderReport,0);

        cutWorkOrderReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem39ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem39ActionPerformed
        InvoiceEntry invoice = InvoiceEntry.getInstance();
        desktopPane.add(invoice,0);

        invoice.setVisible(true);
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem40ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem40ActionPerformed
        InvoiceEntry_Edit invoiceEntry_Edit = InvoiceEntry_Edit.getInstance();
        desktopPane.add(invoiceEntry_Edit,0);

        invoiceEntry_Edit.setVisible(true);
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem41ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem41ActionPerformed
        InvoiceReport invoiceReport = InvoiceReport.getInstance();
        desktopPane.add(invoiceReport,0);

        invoiceReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem42ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem42ActionPerformed
        PrintAndDeliveryQueue printAndDeliveryQueue = PrintAndDeliveryQueue.getInstance();
        desktopPane.add(printAndDeliveryQueue,0);

        printAndDeliveryQueue.setVisible(true);
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem43ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem43ActionPerformed
        Customer_Registration_Edit customer_Registration_Edit = Customer_Registration_Edit.getInstance();
        desktopPane.add(customer_Registration_Edit,0);

        customer_Registration_Edit.setVisible(true);
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem24ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem24ActionPerformed
        EmployeeRegistration employeeRegistration = EmployeeRegistration.getInstance();
        desktopPane.add(employeeRegistration,0);

        employeeRegistration.setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem44ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem44ActionPerformed
        EmployeeViewEdit employeeViewEdit = EmployeeViewEdit.getInstance();
        desktopPane.add(employeeViewEdit,0);

        employeeViewEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        ItemsCreate itemsCreate = ItemsCreate.getInstance();
        desktopPane.add(itemsCreate,0);

        itemsCreate.setVisible(true);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        // TODO add your handling code here:
        ItemsEdit itemsEdit = ItemsEdit.getInstance();
        desktopPane.add(itemsEdit,0);

        itemsEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItem45ActionPerformed
    
    public static void writetrialvalue()
    {
        
        Connection con = DatabaseConnection.createConnection();
        
        try
        {
            
            String sql1="TRUNCATE trialcheck";
            PreparedStatement stmt1 = con.prepareStatement(sql1);
            stmt1.executeUpdate();

            String sql2="INSERT INTO trialcheck(checkstring,value) values(?,?)";
            PreparedStatement stmt2 = con.prepareStatement(sql2);   
            stmt2.setString(1,"#check#");
            //stmt2.setInt(2,RunnableDemo.newtimevalue);
            stmt2.setString(2,LicenceCheck.encryptdata(Integer.toString(RunnableDemo.newtimevalue)));
           
            stmt2.executeUpdate();
            
        }
        catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
            
        }
        finally
        {

            if(con!=null)
            {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                    System.out.println(ex);
                }

            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NewMDIApplication().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    public static javax.swing.JLabel desktopbg_jlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JPopupMenu.Separator jSeparator25;
    private javax.swing.JPopupMenu.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator29;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator30;
    private javax.swing.JPopupMenu.Separator jSeparator31;
    private javax.swing.JPopupMenu.Separator jSeparator32;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel licence_desc_jl;
    // End of variables declaration//GEN-END:variables

}

class RunnableDemo implements Runnable {
   
    private Thread t;
    private String threadName;
    static int timeincrement = 1;
    static int newtimevalue;
    
    RunnableDemo( String name){
       threadName = name;
       System.out.println("Creating: " +  threadName );
    }
    public void run() {
      
        try {
     
            Connection con = DatabaseConnection.createConnection();
            Statement stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery(" SELECT value FROM trialcheck ");
            if(rs1.first())
            {
                
                int timevalue = Integer.parseInt(LicenceCheck.decryptdata(rs1.getString("value")));
                
                for(;;)
                {

                    newtimevalue = timevalue + timeincrement++;
                    
                    int day = (newtimevalue/(24*60))+1;
                    
                    int trialperiod_to_days = (LicenceCheck.trialperiod/(24*60))+1;
                    int remaining_days = trialperiod_to_days - day;

                    System.out.println("NewTimeValue: "+newtimevalue);
                    System.out.println("Remaining: "+remaining_days);

                    if(newtimevalue >= LicenceCheck.trialperiod)
                    {

                        JOptionPane.showMessageDialog(null,"Trial Period Over. Program need to stop.","Stop",JOptionPane.INFORMATION_MESSAGE);
                        NewMDIApplication.writetrialvalue();
                        System.exit(0);
//                        break;

                    }
                    
                    Thread.sleep(60000);
                    
                }
            }
            
        } catch (Exception e) {
         
            System.out.println("Thread " +  threadName + " interrupted.");
        
        }
     
   }
   
   public void start ()
   {
      
        if (t == null)
        {
            
            t = new Thread (this, threadName);
            t.start ();
            
        }
      
   }

}